### PR TITLE
versions bump

### PR DESCRIPTION
**Pull request by andreaTP**
was asked to bump to fastparse 0.4.4
and here you have

### CODE REVIEW

**Comment by LogicalTime** [comment]
+1 yay

**Comment by LogicalTime** [comment]
Could we get a release? The fastparse version bump was important for me. The Scalapb version required for SBT 1.x uses fastparse 0.4.4 and if there versions don't match exactly I get linking errors on the Scalajs side.

**Comment by evacchi** [comment]
@mfirry can you cut a release?

**Comment by mfirry** [comment]
Done! Enjoy `0.1.10`!

**Comment by LogicalTime** [comment]
Fastparse just bumped to a binary compatible 1.0.0 which is identical to 0.4.4. So bump that dependency when you get a chance. With your upgrade to 0.4.4 you are already good with binary compatibility going forward. The bump will just help with dependency resolution error messages.

**Pull request merged**
